Repository gardener/garden-setup, pull requests merged in 2019-09, with the labels that each got.

#92 Prepare finalize
  README.md
  acre.yaml
  bin/installation-handler
  components/cert-manager/controller/component.yaml
  components/cert-manager/controller/deployment.yaml
  components/cert-manager/solver/component.yaml
  components/cert-manager/solver/deployment.yaml
  components/dashboard/component.yaml
  components/dashboard/deployment.yaml
  components/dns-controller/component.yaml
  components/dns-controller/deployment.yaml
  components/gardener/extensions/action
  components/gardener/extensions/component.yaml
  components/gardener/runtime/component.yaml
  components/gardener/runtime/deployment.yaml
  components/gardener/virtual/component.yaml
  components/gardener/virtual/deployment.yaml
  components/identity/component.yaml
  components/identity/deployment.yaml
  docs/extended/README.md
  docs/extended/installation-handler.md
  plugins/chart-checkout/plugin
Labels: needs/ok-to-test, test/integration

#94 fix deletion process without gen folder
  components/gardener/virtual/deployment.yaml
  components/gardener/virtual/export.yaml
Labels: needs/ok-to-test

#93 Add installation handler to integration tests
  .ci/component_descriptor
  .test-defs/CreateGarden.yaml
  .test-defs/DeleteGarden.yaml
  .test-defs/UpgradeGarden.yaml
  test/acre.yaml
  test/scripts/create
  test/scripts/delete
  test/scripts/upgrade
  test/testruns/default/templates/testrun-default.yaml
Labels: needs/ok-to-test, platform/aws, platform/gcp, test/integration

#96 [ci:component:github.com/gardener/gardener:0.28.0->0.29.1]
  .ci/set_dependency_version
  GARDENER_VERSION
  acre.yaml
  components/gardencontent/coreproject/deployment.yaml
  components/gardencontent/profiles/deployment.yaml
  components/gardencontent/profiles/lib/create.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
  components/gardencontent/seeds/manifests/seed_manifest.yaml
  components/gardener/extensions/deployment.yaml
  docs/extended/iaas.md
  test/acre.yaml
Labels: needs/ok-to-test

#98 [ci:component:github.com/gardener/gardener:0.29.1->0.29.2]
  GARDENER_VERSION
  acre.yaml
  components/gardencontent/seeds/manifests/seed_manifest.yaml
Labels: base/aws, needs/ok-to-test, test/integration

#103 Performance improvements
  acre.yaml
  components/cert-manager/cert/action
  components/gardencontent/profiles/deployment.yaml
  components/gardencontent/seeds/seeds/component.yaml
  components/gardencontent/seeds/seeds/deployment.yaml
  components/gardencontent/seeds/shoots/action
  components/gardencontent/seeds/shoots/component.yaml
  components/gardencontent/seeds/shoots/deployment.yaml
  components/gardencontent/seeds/soils/action
  components/gardener/runtime/action
  docs/extended/iaas.md
  plugins/chart-checkout/plugin
  plugins/shoot-check/plugin
Labels: needs/ok-to-test, test/integration

#104 Add support for multiple kubernetes versions in tests
  test/acre.yaml
Labels: needs/ok-to-test

#107 Change Issuer to ClusterIssuer and minor fixes
  components/cert-manager/cert/deployment.yaml
  components/cert-manager/controller/deployment.yaml
  components/dashboard/deployment.yaml
  components/gardencontent/seeds/manifests/shoot_manifest.yaml
  components/gardencontent/seeds/provider/aws/shoot.yaml
  components/gardencontent/seeds/seeds/deployment.yaml
  components/gardencontent/seeds/shoots/deployment.yaml
  components/gardencontent/seeds/soils/deployment.yaml
  components/gardener/virtual/deployment.yaml
Labels: needs/ok-to-test
