Repository gardener/garden-setup, pull requests merged in 2019-08, with the labels that each got.

#80 [ci:component:github.com/gardener/gardener:0.27.1->0.27.4]
  GARDENER_VERSION
Labels: needs/ok-to-test, test/integration

#81 Add Pull-Request script to trigger integration test
  .ci/pr_labels.py
  test/testruns/default/templates/_aws-shoot.tpl
  test/testruns/default/templates/_az-shoot.tpl
  test/testruns/default/templates/_gcp-shoot.tpl
  test/testruns/default/templates/testrun-default.yaml
  test/testruns/default/values.yaml
Labels: needs/ok-to-test, platform/aws, test/integration

#86 update cert-manager to v0.9.1 and dns-controller-manager to 0.6.1
  acre.yaml
Labels: reviewed/ok-to-test

#84 [ci:component:github.com/gardener/gardener:0.27.4->0.27.6]
  GARDENER_VERSION
  acre.yaml
Labels: needs/ok-to-test, platform/aws, platform/gcp, test/integration

#85 Add integration test support for specific base clusters in PR's
  .ci/it-prepare.py
  .ci/pipeline_definitions
  .ci/tm-test
  test/acre.yaml
  test/scripts/delete
  test/testruns/default/templates/_aws-shoot.tpl
  test/testruns/default/templates/_az-shoot.tpl
  test/testruns/default/templates/_garden-config.tpl
  test/testruns/default/templates/_gcp-shoot.tpl
  test/testruns/default/templates/testrun-default.yaml
  test/testruns/default/values.yaml
Labels: area/quality, base/aws, needs/ok-to-test, platform/aws, platform/gcp, test/integration

#90 [ci:component:github.com/gardener/gardener:0.27.6->0.28.0]
  GARDENER_VERSION
  acre.yaml
  components/gardener/extensions/component.yaml
  components/gardener/extensions/deployment.yaml
Labels: needs/ok-to-test, test/integration

#91 add possibility to specify region for AWS route53 in credentials
  components/dns-controller/deployment.yaml
  components/gardener/virtual/deployment.yaml
Labels: reviewed/ok-to-test
