Repository gardener/garden-setup, pull requests merged in 2020-10, with the labels that each got.

#312 enable custom load balancer service annotations to the ingress contro…
  README.md
  acre.yaml
  components/ingress-controller/chart/templates/00-ingress-controller.yaml
  components/ingress-controller/deployment.yaml
Labels: reviewed/lgtm, size/xs

#313 customize the settings for the seeds via acre.yaml
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardencontent/seeds/soils/deployment.yaml
  docs/extended/iaas.md
Labels: needs/changes, size/xs

#317 make dns ttl configurable
  acre.yaml
  components/cert-manager/controller/deployment.yaml
  components/gardener/extensions/deployment.yaml
  components/ingress-controller/deployment.yaml
Labels: reviewed/lgtm, size/xs

#316 Fix link in the docs to the 30-cloudprofile.yaml file
  docs/extended/iaas.md
Labels: reviewed/lgtm, size/xs

#311 add nodeVolumeAttachLimit option in iaas - openstack
  acre.yaml
  components/gardencontent/profiles/provider/openstack/iaas.yaml
  docs/extended/iaas.md
Labels: reviewed/lgtm, size/xs

#318 Improve the table syntax in the README file
  README.md
Labels: reviewed/lgtm, size/m

#320 Document the use of semantic versions for OpenStack images
  docs/extended/iaas.md
Labels: reviewed/lgtm, size/xs

#322 remove coreos / update machine images / update kubernetes versions
  acre.yaml
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
  components/gardencontent/seeds/manifests/shoot_manifest.yaml
  components/gardener/extensions/component.yaml
  components/gardener/extensions/deployment.yaml
  dependency-versions.yaml
  docs/extended/gardener.md
Labels: needs/review, size/m

#323 Remove coreos from "Advanced Configuration Options for 'landscape.iaas'"
  docs/extended/iaas.md
Labels: reviewed/lgtm, size/xs

#324 Fix wrong line specification for example in gardener-extension-netwoking-calico
  docs/extended/gardener.md
Labels: size/xs

#326 Update Gardener extensions
  README.md
  dependency-versions.yaml
Labels: needs/review, size/xs
