Repository gardener/garden-setup, pull requests merged in 2021-02, with the labels that each got.

#371 Update
  dependency-versions.yaml
Labels: needs/review, size/xs

#373 configure pipeline to create update pull requests against the 'update' branch
  .ci/branch.cfg
  .ci/pipeline_definitions
Labels: needs/review, size/m

#378 Upgrade github_com_gardener_gardener-extension-os-suse-chost
  dependency-versions.yaml
Labels: needs/review, size/xs

#379 Upgrade github_com_gardener_gardener-extension-os-ubuntu
  dependency-versions.yaml
Labels: needs/review, size/xs

#380 Upgrade github_com_gardener_gardener-extension-os-gardenlinux
  dependency-versions.yaml
Labels: needs/review, size/xs

#381 Upgrade github_com_gardener_gardener-extension-provider-aws
  dependency-versions.yaml
Labels: needs/review, size/xs

#383 Upgrade github_com_gardener_gardener-extension-provider-openstack
  dependency-versions.yaml
Labels: needs/review, size/xs

#384 Upgrade github_com_gardener_gardener-extension-provider-azure
  dependency-versions.yaml
Labels: needs/review, size/xs

#385 Upgrade github_com_gardener_gardener
  dependency-versions.yaml
Labels: needs/review, size/xs

#386 Upgrade github_com_gardener_gardener-extension-provider-aws
  dependency-versions.yaml
Labels: needs/review, size/xs

#387 VMware fixes
  acre.yaml
  components/cert-manager/controller/deployment.yaml
  components/gardener/extensions/deployment.yaml
  docs/extended/iaas.md
Labels: needs/review, size/xs

#388 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#394 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#396 fix dns-controller-manager configuration
  components/dns-controller/deployment.yaml
Labels: needs/review, size/xs

#399 additional gardenlet featuregates
  acre.yaml
Labels: reviewed/lgtm, size/xs
