Repository gardener/garden-setup, pull requests merged in 2021-07, with the labels that each got.

#535 Add resourcequota controller to kube-controller-manager
  components/kube-apiserver/chart/templates/deployment-kube-apiserver.yaml
Labels: lifecycle/stale, reviewed/lgtm, size/xs

#550 Fix a bug in deployment of gardener-metrics-exporter
  components/monitoring/gardener-metrics-exporter/deployment.yaml
Labels: reviewed/lgtm, size/xs

#551 Upgrade Gardener to v1.25.2
  dependency-versions.yaml
Labels: needs/review, size/xs

#555 Upgrade Gardener, extensions, kubernetes versions and machine images
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
  dependency-versions.yaml
Labels: needs/review, size/m

#578 Iaas cidr docs improvement
  docs/extended/iaas.md
Labels: reviewed/lgtm, size/xs

#580 Upgrade Gardener, extensions, and default kubernetes versions
  components/gardencontent/profiles/manifests/manifest.yaml
  dependency-versions.yaml
Labels: needs/review, size/s
