Repository gardener/garden-setup, pull requests merged in 2021-03, with the labels that each got.

#402 dns provider infoblox: optional fields for credentials
  README.md
  acre.yaml
Labels: reviewed/lgtm, size/xs

#411 use credentials instead of providerConfig for infoblox DNS
  README.md
  acre.yaml
Labels: reviewed/lgtm, size/s

#417 fix bug when deactivating etcd backups for GCS
  components/etcd/cluster/deployment.yaml
Labels: needs/review, size/xs

#418 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs
