Repository gardener/garden-setup, pull requests merged in 2021-04, with the labels that each got.

#431 Fix 430 ingress competing gcp lb
  components/kube-apiserver/chart/templates/service-kube-apiserver-ingress.yaml
Labels: reviewed/lgtm, size/xs

#434 fix dex supported connectors link
  docs/extended/identity.md
Labels: needs/review, size/xs

#435 Update
  dependency-versions.yaml
Labels: needs/review, size/xs

#389 use seed managed ingress feature instead of shoot addon
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardencontent/seeds/manifests/shoot_manifest.yaml
  components/gardencontent/seeds/seeds/deployment.yaml
  components/gardencontent/seeds/soils/deployment.yaml
Labels: needs/review, size/s

#440 bugfix: landscape.identity.users not defined
  components/dashboard/deployment.yaml
Labels: needs/review, size/xs

#443 Upgrade Gardener and extensions
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardencontent/seeds/seeds/deployment.yaml
  components/gardencontent/seeds/soils/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/s
