Repository gardener/garden-setup, pull requests merged in 2021-05, with the labels that each got.

#455 Upgrade Gardener and extensions
  components/dns-controller/manifests/provider_secret.yaml
  dependency-versions.yaml
Labels: needs/review, size/xs

#452 upgrade terraform manifests to terraform 0.13
  components/etcd/backupinfra/provider/abs/versions.tf
  components/etcd/backupinfra/provider/gcs/versions.tf
  components/etcd/backupinfra/provider/s3/versions.tf
  components/etcd/backupinfra/provider/swift/versions.tf
Labels: needs/review, size/xs

#479 Vsphere tkc base cluster
  docs/extended/vsphere-tkc-base-cluster.md
Labels: reviewed/lgtm, size/s

#484 Update extended Doc with tanzu
  docs/extended/README.md
Labels: reviewed/lgtm, size/xs

#497 Upgrade Gardener and dependencies
  components/dashboard/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/s

#445 Update cert manager to v1.3.1
  acre.yaml
  components/cert-manager/controller/deployment.yaml
Labels: lifecycle/rotten, reviewed/lgtm, size/xs

#502 Fix gardener #4108
  components/ingress-controller/deployment.yaml
Labels: needs/review, size/xs
