Repository gardener/garden-setup, pull requests merged in 2021-11, with the labels that each got.

#652 Make gardenlet logging configurable
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  docs/extended/iaas.md
Labels: needs/review, size/xs

#651 Enhance resource limits and requests configuration
  README.md
  acre.yaml
  components/dashboard/deployment.yaml
  components/etcd/cluster/chart/templates/statefulset-etcd.yaml
  components/etcd/cluster/chart/values.yaml
  components/etcd/cluster/deployment.yaml
  components/gardener/virtual/deployment.yaml
  docs/extended/dashboard.md
Labels: needs/changes, needs/review, size/s

#653 Allow adding custom scrape_configs for prometheus
  acre.yaml
  components/monitoring/prometheus/deployment.yaml
  components/monitoring/prometheus/manifests/02-prometheus-config.yaml
  docs/extended/monitoring.md
Labels: reviewed/lgtm, size/s

#649 Add remote_write feature configuration
  acre.yaml
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardencontent/seeds/soils/deployment.yaml
  components/monitoring/prometheus/deployment.yaml
  components/monitoring/prometheus/manifests/02-prometheus-config.yaml
  docs/extended/monitoring.md
Labels: reviewed/lgtm, size/s

#654 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#655 migrate ingress resources to networking.k8s.io/v1
  components/kube-apiserver/chart/templates/service-kube-apiserver-ingress.yaml
  components/monitoring/grafana/manifests/60-ingress.yaml
  components/monitoring/prometheus/manifests/50-ingress.yaml
Labels: needs/review, size/xs

#660 add template for dashboard ingress annotations
  components/dashboard/deployment.yaml
  docs/extended/dashboard.md
Labels: reviewed/lgtm, size/xs
