Repository gardener/garden-setup, pull requests merged in 2022-03, with the labels that each got.

#734 Add ectd maxBackups and schedule as optional configurable parameters
  README.md
  acre.yaml
  components/etcd/cluster/deployment.yaml
Labels: needs/review, size/xs

#738 Upgrade Gardener and extensions
  README.md
  acre.yaml
  components/gardencontent/gardenproject/deployment.yaml
  components/kube-apiserver/chart/templates/deployment-kube-apiserver.yaml
  components/kube-apiserver/chart/templates/secret-kube-apiserver-static-token.yaml
  components/kube-apiserver/chart/values.yaml
  components/kube-apiserver/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/s

#739 Make all cert-manager image registries configurable
  acre.yaml
  components/cert-manager/controller/deployment.yaml
Labels: reviewed/lgtm, size/xs
