Repository gardener/garden-setup, pull requests merged in 2022-09, with the labels that each got.

#873 Update Readme
  README.md
Labels: reviewed/lgtm, size/s

#880 Upgrade Gardener, extensions, and dependencies
  SOW_VERSION
  acre.yaml
  components/etcd/backupinfra/provider/abs/main.tf
  components/etcd/backupinfra/provider/gcs/main.tf
  components/etcd/backupinfra/provider/s3/main.tf
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardener/virtual/deployment.yaml
  components/ingress-controller/deployment.yaml
  components/kube-apiserver/chart/templates/deployment-kube-apiserver.yaml
  components/kube-apiserver/chart/values.yaml
  components/kube-apiserver/deployment.yaml
  components/terminals/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/s

#882 Update
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/profiles/provider/alicloud/iaas.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
Labels: needs/review, needs/second-opinion, size/l

#884 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#885 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#889 Upgrade Gardener and extensions
  components/kube-apiserver/chart/templates/service-kube-apiserver-ingress.yaml
  components/kube-apiserver/deployment.yaml
  dependency-versions.yaml
  plugins/finalize/plugin
Labels: needs/review, size/s

#891 Upgrade Gardener and extensions and refactor 'sow convertkubeconfig'
  README.md
  dependency-versions.yaml
  lib/sow.sh
Labels: needs/review, size/m

#894 technical debt removal
  .ci/component_descriptor
  .ci/set_dependency_version
  acre.yaml
  components/dns-controller/component.yaml
  components/dns-controller/deployment.yaml
  components/gardener/extensions/component.yaml
  components/gardener/extensions/deployment.yaml
  components/kube-apiserver/deployment.yaml
  dependency-versions.yaml
  docs/extended/gardener.md
Labels: needs/review, size/m
