Repository gardener/garden-setup, pull requests merged in 2022-04, with the labels that each got.

#747 Enable custom overwrites for controllers config of GCM
  acre.yaml.example
  components/gardener/virtual/deployment.yaml
Labels: reviewed/lgtm, size/xs

#757 Upgrade Gardener, extensions, and default k8s versions and machine images
  SOW_VERSION
  acre.yaml
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
  components/gardencontent/seeds/soils/action
  components/gardener/extensions/deployment.yaml
  components/ingress-controller/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/m

#758 fix controllers merge
  VERSION
  components/gardener/virtual/deployment.yaml
Labels: needs/review, size/xs

#759 upgrade Gardener to v1.40.4
  dependency-versions.yaml
Labels: needs/review, size/xs
