Repository gardener/garden-setup, pull requests merged in 2023-02, with the labels that each got.

#1008 Remove the use of the enableBasicAuthentication field
  components/gardencontent/seeds/manifests/shoot_manifest.yaml
Labels: reviewed/lgtm, size/xs

#1009 Upgrade Gardener and extensions
  components/dashboard/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, size/xs

#1011 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#970 actually use etcd-events for events
  components/kube-apiserver/chart/templates/deployment-kube-apiserver.yaml
Labels: reviewed/lgtm, size/xs

#1014 Upgrade Gardener and extensions
  dependency-versions.yaml
Labels: needs/review, size/xs

#1017 Upgrade Gardener and dashboard
  SOW_VERSION
  acre.yaml
  components/etcd/backupinfra/provider/s3/main.tf
  components/gardencontent/profiles/manifests/manifest.yaml
  components/gardencontent/profiles/provider/alicloud/iaas.yaml
  components/gardencontent/profiles/provider/aws/iaas.yaml
  components/gardencontent/profiles/provider/azure/iaas.yaml
  components/gardencontent/profiles/provider/gcp/iaas.yaml
  components/gardencontent/seeds/manifests/seed_manifests.yaml
  components/gardencontent/seeds/manifests/shoot_manifest.yaml
  components/gardencontent/seeds/seeds/deployment.yaml
  components/gardencontent/seeds/soils/deployment.yaml
  dependency-versions.yaml
Labels: needs/review, needs/second-opinion, size/xl
